trivy y secretos

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,17 +18,32 @@ jobs:
         with:
           node-version: '18'
 
-      - name: Instalar dependencias y Lint
+      - name: Instalar dependencias
         run: |
           cd app
           npm install
-          #npm
 
       - name: Build de Imagen Docker
         run: |
           docker build -t mi-hola-mundo:${{ github.sha }} ./app
 
+      - name: Escaneo de Vulnerabilidades (Trivy)
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: 'mi-hola-mundo:${{ github.sha }}'
+          format: 'table'
+          exit-code: '1'
+          severity: 'CRITICAL,HIGH'
+
+      - name: Validar uso de Secretos en Despliegue
+        run: |
+          if grep -i "password:" k8s/deployment.yaml; then
+            echo "ERROR: Se detectó un password en texto plano en el manifiesto."
+            exit 1
+          else
+            echo "Validación exitosa: Los secretos se manejan mediante referencias."
+          fi
+
       - name: Validar Manifiestos K8s
         run: |
-          # verificación yaml
           docker run --rm -v $(pwd)/k8s:/apps alpine/kube-score:latest score /apps/*.yaml || true
